# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Bad'), (2, '2 Poor'), (3, '3 Fair'), (4, '4 Good'), (5, '5 Excellent')])),
            ],
        ),
        migrations.CreateModel(
            name='Stimuli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('birth_year', models.IntegerField(blank=True)),
                ('hearing_loss', models.BooleanField()),
                ('subjective_test', models.IntegerField(blank=True, choices=[(1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')])),
                ('speech_test', models.IntegerField(blank=True, choices=[(1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')])),
                ('connected', models.BooleanField()),
                ('volume', models.IntegerField(blank=True)),
                ('access_training', models.BooleanField(default=False)),
                ('access_acr', models.DateTimeField(blank=True)),
                ('ratings', models.ManyToManyField(through='audiocrowd.Rating', to='audiocrowd.Stimuli')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Stimuli'),
        ),
        migrations.AddField(
            model_name='rating',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Worker'),
        ),
    ]
