# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldStandardAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(1, '1 Bad'), (2, '2 Poor'), (3, '3 Fair'), (4, '4 Good'), (5, '5 Excellent')])),
                ('set_nr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoldStandardQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expected_answer', models.IntegerField(choices=[(1, '1 Bad'), (2, '2 Poor'), (3, '3 Fair'), (4, '4 Good'), (5, '5 Excellent')])),
            ],
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='ratings',
            new_name='acr_ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='set_nr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldstandardanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.GoldStandardQuestions'),
        ),
        migrations.AddField(
            model_name='goldstandardanswers',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='gold_standard_answers',
            field=models.ManyToManyField(through='audiocrowd.GoldStandardAnswers', to='audiocrowd.GoldStandardQuestions'),
        ),
    ]
