# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0002_auto_20170829_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='finished_sets',
            field=models.IntegerField(default=0),
        ),
    ]
