# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0003_worker_finished_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimuli',
            name='path',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimuli',
            name='type',
            field=models.CharField(choices=[('img', 'Image'), ('aud', 'Audio'), ('vid', 'Video'), ('txt', 'Text')], default='img', max_length=3),
            preserve_default=False,
        ),
    ]
