# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0004_auto_20170829_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldstandardquestions',
            name='path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldstandardquestions',
            name='type',
            field=models.CharField(choices=[('img', 'Image'), ('aud', 'Audio'), ('vid', 'Video'), ('txt', 'Text')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
