# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0005_auto_20170830_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birth_year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hearing_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='speech_test',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')], default=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='subjective_test',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')], default=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='volume',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
