# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0006_auto_20170831_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='access_acr',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
