# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0007_auto_20170831_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='qualification_done',
            field=models.BooleanField(default=False),
        ),
    ]
