# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0009_auto_20170831_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='speech_test',
            field=models.IntegerField(choices=[(0, 'Never'), (1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')], default=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='subjective_test',
            field=models.IntegerField(choices=[(0, 'Never'), (1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')], default=1),
        ),
    ]
