# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0010_auto_20170831_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimuli_per_job', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
