# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0011_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birth_year',
            field=models.DateField(default=0),
        ),
    ]
