# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0012_auto_20170908_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='access_window',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_year',
            field=models.DateField(default='1930-01-01'),
        ),
    ]
