# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0013_auto_20170908_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_nr', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('invalid_set', models.BooleanField(default=False)),
                ('calibrated_volume', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='goldstandardanswers',
            name='set_nr',
        ),
        migrations.RemoveField(
            model_name='goldstandardanswers',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='set_nr',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='acr_ratings',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='finished_sets',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='gold_standard_answers',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='volume',
        ),
        migrations.AddField(
            model_name='goldstandardanswers',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ratingset',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Worker'),
        ),
        migrations.AddField(
            model_name='goldstandardanswers',
            name='rating_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.RatingSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.RatingSet'),
            preserve_default=False,
        ),
    ]
