# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0014_auto_20170911_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('mw', 'Microworkers')], max_length=3)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], max_length=3)),
                ('stimuli', models.ManyToManyField(to='audiocrowd.Stimuli')),
            ],
        ),
    ]
