# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0015_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingset',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Campaign'),
            preserve_default=False,
        ),
    ]
