# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0017_campaign_gold_standard_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='training_stimuli',
            field=models.ManyToManyField(related_name='training_stimuli', to='audiocrowd.Stimuli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='stimuli',
            field=models.ManyToManyField(related_name='stimuli', to='audiocrowd.Stimuli'),
        ),
    ]
