# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0020_campaign_calibrate_stimulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birth_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='connected',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hearing_loss',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='speech_test',
            field=models.IntegerField(choices=[(0, 'Never'), (1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')], null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='subjective_test',
            field=models.IntegerField(choices=[(0, 'Never'), (1, '1 Month'), (2, '3 Months'), (3, '6 Months'), (4, '9 Months'), (5, '1 year or more')], null=True),
        ),
    ]
