# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0021_auto_20171121_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='connected',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hearing_loss',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
    ]
