# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0022_auto_20171121_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_window', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='SubCampaignTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='vcode_key',
            field=models.CharField(default='No key', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='connected',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hearing_loss',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='subcampaigntracker',
            name='sub_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Campaign'),
        ),
        migrations.AddField(
            model_name='subcampaigntracker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Worker'),
        ),
        migrations.AddField(
            model_name='subcampaign',
            name='parent_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Campaign'),
        ),
    ]
