# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0023_auto_20171121_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcampaign',
            name='sub_campaign_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
