# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0024_subcampaign_sub_campaign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingset',
            name='campaign',
        ),
        migrations.AddField(
            model_name='ratingset',
            name='sub_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.SubCampaign'),
            preserve_default=False,
        ),
    ]
