# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0025_auto_20171121_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldstandardanswers',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='ratingset',
            name='calibrated_volume',
        ),
    ]
