# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0026_auto_20171121_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcampaign',
            name='max_worker_count',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
