# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0028_auto_20171121_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contact_link',
            field=models.CharField(default='http://crowd-square.com/viewtopic.php?f=30&t=18835', max_length=100),
        ),
        migrations.AddField(
            model_name='configuration',
            name='default_campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.Campaign'),
        ),
    ]
