# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0030_auto_20171128_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='listening_device',
            field=models.IntegerField(choices=[(0, 'Loudspeaker'), (1, 'Head-set/phones'), (2, 'In-Ear Headset')], null=True),
        ),
    ]
