# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0032_auto_20171219_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='questions',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
