# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0033_worker_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='background_noise',
            field=models.IntegerField(choices=[(5, 'Not noticeable.'), (4, 'Slightly noticeable.'), (3, 'Noticeable but not intrusive.'), (2, 'Somewhat intrusive.'), (1, 'Very intrusive.')], null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='hearing',
            field=models.IntegerField(choices=[(0, 'I have a normal hearing ability.'), (1, 'I have difficulties keeping up with conversations, especially in noisy surroundings.'), (2, 'I have difficulty keeping up with conversations when I am not using a hearing aid.'), (3, 'I rely on lip-reading even when I am using hearing aids.')], null=True),
        ),
    ]
