# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0034_auto_20180717_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingset',
            name='background_noise',
            field=models.IntegerField(choices=[(5, 'Not noticeable.'), (4, 'Slightly noticeable.'), (3, 'Noticeable but not intrusive.'), (2, 'Somewhat intrusive.'), (1, 'Very intrusive.')], null=True),
        ),
    ]
