# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0035_ratingset_background_noise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='background_noise',
        ),
    ]
