# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiocrowd', '0036_remove_worker_background_noise'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadphoneCheckStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('expected_answer', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='ratingset',
            name='headphone_check_answer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='headphone_check',
            field=models.ManyToManyField(to='audiocrowd.HeadphoneCheckStimulus'),
        ),
        migrations.AddField(
            model_name='ratingset',
            name='headphone_check_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audiocrowd.HeadphoneCheckStimulus'),
        ),
    ]
